apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: akshay-sample-cluster
  region: us-east-1

vpc:
  id: "vpc-11111"
  subnets:
    public:
      us-east-1a:
          id: "subnet-0153e560b3129a696"
      us-east-1b:
          id: "subnet-009fa0199ec203c37"
      us-east-1c:
          id: "subnet-009fa0199ec203c37"   

nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    desiredCapacity: 2

# Install kubectl
# Install eksctl
# Install aws-iam-authenticator
# eksctl create cluster -f eks-create-cluster.yaml    

# kubectl get pods
# kubectl get pods -o wide
# kubectl get svc
# NodePort - Take that port (30000-32000) add it to your security group of the node open it to your Public IP or 0.0.0.0/0
# kubectl get deploy
