apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: akshay-sample-cluster
  region: us-east-1

vpc:
  id: "vpc-11111"
  subnets:
    public:
      us-east-1a:
          id: "subnet-0153e560b3129a696"
      us-east-1b:
          id: "subnet-009fa0199ec203c37"
      us-east-1c:
          id: "subnet-009fa0199ec203c37"   

nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    desiredCapacity: 2

# Install kubectl
# Install eksctl
# Install aws-iam-authenticator
# eksctl create cluster -f eks-create-cluster.yaml    